package AntVillage;

import java.awt.*;

public class Bienvenida extends javax.swing.JFrame {

    String alimen;
    int alimento;

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        CrearInterfaz();
    }

    public void CrearInterfaz() {

        Bienvenida.setOpaque(true);
        Bienvenida.setFont(new Font("Times New Roman", Font.PLAIN, 24));

        Escogencia_A.setOpaque(true);
        Escogencia_A.setFont(new Font("Times New Roman", Font.PLAIN, 18));

        c_alimento.setOpaque(true);
        c_alimento.setFont(new Font("Times New Roman", Font.PLAIN, 15));

        c_alimento1.setOpaque(true);
        c_alimento1.setFont(new Font("Times New Roman", Font.PLAIN, 15));

        ali.setFont(new Font("Times New Roman", Font.ROMAN_BASELINE, 15));

        Escogencia_C.setOpaque(true);
        Escogencia_C.setFont(new Font("Times New Roman", Font.PLAIN, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        categorias = new javax.swing.ButtonGroup();
        panelPresentacion = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JLabel();
        Escogencia_A = new javax.swing.JLabel();
        c_alimento = new javax.swing.JLabel();
        c_alimento1 = new javax.swing.JLabel();
        ali = new javax.swing.JTextField();
        Escogencia_C = new javax.swing.JLabel();
        Boton_validar = new javax.swing.JButton();
        elegir_grafo3 = new javax.swing.JRadioButton();
        elegir_grafo1 = new javax.swing.JRadioButton();
        elegir_grafo2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ventana_bienvenida");

        panelPresentacion.setBackground(new java.awt.Color(0, 255, 255));
        panelPresentacion.setForeground(new java.awt.Color(0, 255, 255));

        Bienvenida.setText("Bienvenid@ a AntVillage");

        Escogencia_A.setText("Digite la cantidad de alimento que desea para la partida:");

        c_alimento.setText("Cantidad de alimento:");

        c_alimento1.setText("Inserte un número menor o igual que 5");

        Escogencia_C.setText("Escoga UNA de las categorias dadas");

        Boton_validar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Boton_validar.setText("Jugar");
        Boton_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_validarActionPerformed(evt);
            }
        });

        categorias.add(elegir_grafo3);
        elegir_grafo3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        elegir_grafo3.setText("Grafo de 9 nodos");

        categorias.add(elegir_grafo1);
        elegir_grafo1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        elegir_grafo1.setText("Grafo de 5 nodos");

        categorias.add(elegir_grafo2);
        elegir_grafo2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        elegir_grafo2.setText("Grafo de 7 nodos");

        javax.swing.GroupLayout panelPresentacionLayout = new javax.swing.GroupLayout(panelPresentacion);
        panelPresentacion.setLayout(panelPresentacionLayout);
        panelPresentacionLayout.setHorizontalGroup(
                panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(elegir_grafo1)
                                .addGap(77, 77, 77)
                                .addComponent(elegir_grafo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(elegir_grafo3)
                                .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPresentacionLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton_validar)
                                .addGap(264, 264, 264))
                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(269, 269, 269)
                                                .addComponent(ali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(167, 167, 167)
                                                .addComponent(Bienvenida))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(225, 225, 225)
                                                .addComponent(c_alimento))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(Escogencia_A))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Escogencia_C)
                                                        .addComponent(c_alimento1))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPresentacionLayout.setVerticalGroup(
                panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(Bienvenida)
                                .addGap(36, 36, 36)
                                .addComponent(Escogencia_A)
                                .addGap(51, 51, 51)
                                .addComponent(c_alimento1)
                                .addGap(47, 47, 47)
                                .addComponent(c_alimento)
                                .addGap(28, 28, 28)
                                .addComponent(ali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(Escogencia_C)
                                .addGap(37, 37, 37)
                                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(elegir_grafo1)
                                        .addComponent(elegir_grafo2)
                                        .addComponent(elegir_grafo3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(Boton_validar)
                                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void Boton_validarActionPerformed(java.awt.event.ActionEvent evt) {

        alimen = ali.getText();
        alimento = Integer.parseInt(alimen);
        if (elegir_grafo1.isSelected() == true) {
            if (alimento <= 5){
                Bienvenida.this.dispose();
<<<<<<< HEAD
                //new Juego5().setVisible(true);
=======
                new Juego5().setVisible(true);
>>>>>>> parent of f5de7c6... Creación de las ventanas de juego y modificaciones a la pantalla inicial
            }
        }
        else if (elegir_grafo2.isSelected() == true){
            if (alimento <= 5){
                Bienvenida.this.dispose();
<<<<<<< HEAD
                //new Juego7().setVisible(true);
=======
                new Juego7().setVisible(true);
>>>>>>> parent of f5de7c6... Creación de las ventanas de juego y modificaciones a la pantalla inicial
            }
        }
        else {
            if (alimento <= 5){
                Bienvenida.this.dispose();
<<<<<<< HEAD
                //new Juego9().setVisible(true);
=======
                new Juego9().setVisible(true);
>>>>>>> parent of f5de7c6... Creación de las ventanas de juego y modificaciones a la pantalla inicial
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JButton Boton_validar;
    private javax.swing.JLabel Escogencia_A;
    private javax.swing.JLabel Escogencia_C;
    private javax.swing.JTextField ali;
    private javax.swing.JLabel c_alimento;
    private javax.swing.JLabel c_alimento1;
    private javax.swing.ButtonGroup categorias;
    private javax.swing.JRadioButton elegir_grafo1;
    private javax.swing.JRadioButton elegir_grafo2;
    private javax.swing.JRadioButton elegir_grafo3;
    private javax.swing.JPanel panelPresentacion;
    // End of variables declaration
}