package AntVillage;

import javax.swing.*;
import java.awt.*;

public class Bienvenida extends javax.swing.JFrame {

    String alimen;
    int alimento;

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        categorias = new javax.swing.ButtonGroup();
        panelPresentacion = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JLabel();
        Escogencia_A = new javax.swing.JLabel();
        c_alimento1 = new javax.swing.JLabel();
        ali = new javax.swing.JTextField();
        Escogencia_C = new javax.swing.JLabel();
        Boton_validar = new javax.swing.JButton();
        elegir_grafo3 = new javax.swing.JRadioButton();
        elegir_grafo1 = new javax.swing.JRadioButton();
        elegir_grafo2 = new javax.swing.JRadioButton();
        Boton_registro_partidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ventana_bienvenida");

        panelPresentacion.setBackground(new java.awt.Color(0, 153, 153));

        Bienvenida.setFont(new java.awt.Font("Times New Roman", 1, 18));
        Bienvenida.setText("Bienvenid@ a AntVillage");

        Escogencia_A.setFont(new java.awt.Font("Times New Roman", 1, 18));
        Escogencia_A.setText("Digite la cantidad de alimento que desea para la partida, debe ser igual o menor a 5.");

        ali.setBackground(new java.awt.Color(102, 102, 102));
        ali.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliActionPerformed(evt);
            }
        });

        Escogencia_C.setFont(new java.awt.Font("Times New Roman", 1, 18));
        Escogencia_C.setText("Escoga UNA de las categorias dadas");

        Boton_validar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Boton_validar.setText("Jugar");
        Boton_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_validarActionPerformed(evt);
            }
        });

        categorias.add(elegir_grafo3);
        elegir_grafo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        elegir_grafo3.setText("Grafo de 9 nodos");

        categorias.add(elegir_grafo1);
        elegir_grafo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        elegir_grafo1.setText("Grafo de 5 nodos");

        categorias.add(elegir_grafo2);
        elegir_grafo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        elegir_grafo2.setText("Grafo de 7 nodos");

        Boton_registro_partidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Boton_registro_partidas.setText("Historial de partidas");
        Boton_registro_partidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_registro_partidasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Si desea ver el historial de partidas puede acceder por medio del siguiente botón");

        javax.swing.GroupLayout panelPresentacionLayout = new javax.swing.GroupLayout(panelPresentacion);
        panelPresentacion.setLayout(panelPresentacionLayout);
        panelPresentacionLayout.setHorizontalGroup(
                panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(elegir_grafo1)
                                .addGap(74, 74, 74)
                                .addComponent(elegir_grafo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(elegir_grafo3)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPresentacionLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton_registro_partidas)
                                .addGap(249, 249, 249))
                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(234, 234, 234)
                                                .addComponent(Bienvenida))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(Escogencia_A))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(296, 296, 296)
                                                .addComponent(Boton_validar))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(298, 298, 298)
                                                .addComponent(ali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                                .addGap(183, 183, 183)
                                                .addComponent(Escogencia_C)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPresentacionLayout.setVerticalGroup(
                panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPresentacionLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Bienvenida)
                                .addGap(50, 50, 50)
                                .addComponent(Escogencia_A)
                                .addGap(19, 19, 19)
                                .addComponent(ali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(Escogencia_C)
                                .addGap(38, 38, 38)
                                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(elegir_grafo1)
                                        .addComponent(elegir_grafo2)
                                        .addComponent(elegir_grafo3))
                                .addGap(30, 30, 30)
                                .addComponent(Boton_validar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(Boton_registro_partidas)
                                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void Boton_validarActionPerformed(java.awt.event.ActionEvent evt) {

        alimen = ali.getText();
        alimento = Integer.parseInt(alimen);
        if (elegir_grafo1.isSelected() == true) {
            if (alimento <= 5){
                Bienvenida.this.dispose();
                new Juego5(alimento).setVisible(true);

            }
        }
        else if (elegir_grafo2.isSelected() == true){
            if (alimento <= 5){
                Bienvenida.this.dispose();
                new Juego7(alimento).setVisible(true);

            }
        }
        else {
            if (alimento <= 5){
                Bienvenida.this.dispose();
                new Juego9(alimento).setVisible(true);

            }
        }
    }
    private void Boton_registro_partidasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void aliActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JButton Boton_registro_partidas;
    private javax.swing.JButton Boton_validar;
    private javax.swing.JLabel Escogencia_A;
    private javax.swing.JLabel Escogencia_C;
    private javax.swing.JTextField ali;
    private javax.swing.JLabel c_alimento1;
    private javax.swing.ButtonGroup categorias;
    private javax.swing.JRadioButton elegir_grafo1;
    private javax.swing.JRadioButton elegir_grafo2;
    private javax.swing.JRadioButton elegir_grafo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPresentacion;
    // End of variables declaration
}