package AntVillageGUI;

public class Juego7 extends javax.swing.JFrame {

    String hormiguero = "imagenes/imagen1.png";
    String comida_juego = "imagenes/Comida.png";

    /**
     * Creates new form Juego7
     */
    public Juego7(int alimento) {

        initComponents();

        Comida_Esco.setText(String.valueOf(alimento));

        rsscalelabel.RSScaleLabel.setScaleLabel(A, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(B, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(C, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(D, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(E, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(F, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(G, hormiguero);

        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_A,comida_juego);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_B,comida_juego);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_C,comida_juego);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_D,comida_juego);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_E,comida_juego);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_F,comida_juego);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_G,comida_juego);

    }

    private Juego7() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();
        Comida_A = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        Comida_B = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        Comida_C = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        Comida_D = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        Comida_E = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        Comida_F = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        Comida_G = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        Cantidad = new javax.swing.JLabel();
        Comida_Esco = new javax.swing.JLabel();
        Hormiga_v = new javax.swing.JLabel();
        Hormiga_a = new javax.swing.JLabel();
        Comida_azul = new javax.swing.JLabel();
        Comida_verde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelJuego.setBackground(new java.awt.Color(161, 130, 98));
        panelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(Comida_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 80));
        panelJuego.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 100, 100));
        panelJuego.add(Comida_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, 80));
        panelJuego.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, 100));
        panelJuego.add(Comida_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 80, 80));
        panelJuego.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 100));
        panelJuego.add(Comida_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 80));
        panelJuego.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 100));
        panelJuego.add(Comida_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 80, 80));
        panelJuego.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 100, 100));
        panelJuego.add(Comida_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 80, 80));
        panelJuego.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 101, 100));
        panelJuego.add(Comida_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 80, 80));
        panelJuego.add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 100, 100));

        panelInfo.setBackground(new java.awt.Color(0, 102, 102));

        Cantidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Cantidad.setText("Cantidad de comida escogida:");

        Comida_Esco.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Comida_Esco.setText("..............");

        Hormiga_v.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Hormiga_v.setText("Hormigas Verdes:");

        Hormiga_a.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Hormiga_a.setText("Hormigas Azules:");

        Comida_azul.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Comida_azul.setText("...............");

        Comida_verde.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Comida_verde.setText("...............");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
                panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Cantidad)
                                .addGap(95, 95, 95)
                                .addComponent(Hormiga_v)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(Hormiga_a)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(Comida_Esco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Comida_verde)
                                .addGap(181, 181, 181)
                                .addComponent(Comida_azul)
                                .addGap(32, 32, 32))
        );
        panelInfoLayout.setVerticalGroup(
                panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Cantidad)
                                        .addComponent(Hormiga_v)
                                        .addComponent(Hormiga_a))
                                .addGap(18, 18, 18)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Comida_verde)
                                        .addComponent(Comida_Esco)
                                        .addComponent(Comida_azul))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelJuego.add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Comida_A;
    private javax.swing.JLabel Comida_B;
    private javax.swing.JLabel Comida_C;
    private javax.swing.JLabel Comida_D;
    private javax.swing.JLabel Comida_E;
    private javax.swing.JLabel Comida_Esco;
    private javax.swing.JLabel Comida_F;
    private javax.swing.JLabel Comida_G;
    private javax.swing.JLabel Comida_azul;
    private javax.swing.JLabel Comida_verde;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel G;
    private javax.swing.JLabel Hormiga_a;
    private javax.swing.JLabel Hormiga_v;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelJuego;
    // End of variables declaration
}

