package AntVillageGUI;

import org.netbeans.lib.awtextra.AbsoluteLayout;

import javax.swing.*;

public class Juego9 extends javax.swing.JFrame {
    String hormiguero = "imagenes/Imagen1.png";
    String comida = "imagenes/Comida.png";
    /**
     * Creates new form Juego9
     */
    public Juego9(int alimento) {
        initComponents();
        Comida_Esco.setText(String.valueOf(alimento));

        rsscalelabel.RSScaleLabel.setScaleLabel(A, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_A, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(B, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_B, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(C, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_C, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(D, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_D, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(E, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_E, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(F, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_F, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(G, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_G, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(H, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_H, comida);

        rsscalelabel.RSScaleLabel.setScaleLabel(I, hormiguero);
        rsscalelabel.RSScaleLabel.setScaleLabel(Comida_I, comida);

    }

    private Juego9() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        I = new javax.swing.JLabel();

        Comida_A = new javax.swing.JLabel();
        Comida_B = new javax.swing.JLabel();
        Comida_C = new javax.swing.JLabel();
        Comida_D = new javax.swing.JLabel();
        Comida_E = new javax.swing.JLabel();
        Comida_F = new javax.swing.JLabel();
        Comida_G = new javax.swing.JLabel();
        Comida_H = new javax.swing.JLabel();
        Comida_I = new javax.swing.JLabel();

        panelInfo = new javax.swing.JPanel();
        Cantidad = new javax.swing.JLabel();
        Comida_Esco = new javax.swing.JLabel();
        Hormiga_v = new javax.swing.JLabel();
        Hormiga_a = new javax.swing.JLabel();
        Comida_azul = new javax.swing.JLabel();
        Comida_verde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelJuego.setBackground(new java.awt.Color(161, 130, 98));

        panelJuego.setLayout(new AbsoluteLayout());

        panelJuego.add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 633, -1));
        panelJuego.add(Comida_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 80));
        panelJuego.add(Comida_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 80));
        panelJuego.add(Comida_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 80, 80));
        panelJuego.add(Comida_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 80));
        panelJuego.add(Comida_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 80, 80));
        panelJuego.add(Comida_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 80, 80));
        panelJuego.add(Comida_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 80, 80));
        panelJuego.add(Comida_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 80, 80));
        panelJuego.add(Comida_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 80, 80));

        panelJuego.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 119, 100, 100));
        panelJuego.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 95, 100, 100));
        panelJuego.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 100, 100));
        panelJuego.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 100, 100));
        panelJuego.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 100, 100));
        panelJuego.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 100, 100));
        panelJuego.add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 100, 100));
        panelJuego.add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 100, 100));
        panelJuego.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 100));

        panelInfo.setBackground(new java.awt.Color(0, 102, 102));

        Cantidad.setFont(new java.awt.Font("Times New Roman", 1, 12));
        Cantidad.setText("Cantidad de comida escogida:");

        Comida_Esco.setFont(new java.awt.Font("Times New Roman", 1, 12));
        Comida_Esco.setText("...");

        Hormiga_v.setFont(new java.awt.Font("Times New Roman", 1, 12));
        Hormiga_v.setText("Hormigas Verdes:");

        Hormiga_a.setFont(new java.awt.Font("Times New Roman", 1, 12));
        Hormiga_a.setText("Hormigas Azules:");

        Comida_azul.setFont(new java.awt.Font("Times New Roman", 1, 12));
        Comida_azul.setText("...");

        Comida_verde.setFont(new java.awt.Font("Times New Roman", 1, 12));
        Comida_verde.setText("...");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
                panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInfoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(Cantidad))
                                        .addGroup(panelInfoLayout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(Comida_Esco)))
                                .addGap(72, 72, 72)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Hormiga_v, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Comida_verde, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)))
                                .addGap(74, 74, 74)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Hormiga_a)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Comida_azul)
                                                .addGap(43, 43, 43)))
                                .addGap(84, 84, 84))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad)
                    .addComponent(Hormiga_v)
                    .addComponent(Hormiga_a))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comida_verde)
                    .addComponent(Comida_Esco)
                    .addComponent(Comida_azul))
                .addContainerGap(21, Short.MAX_VALUE))
        );



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Comida_Esco;
    private javax.swing.JLabel Comida_azul;
    private javax.swing.JLabel Comida_verde;
    private javax.swing.JLabel Hormiga_a;
    private javax.swing.JLabel Hormiga_v;
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel G;
    private javax.swing.JLabel H;
    private javax.swing.JLabel I;

    private javax.swing.JLabel Comida_A;
    private javax.swing.JLabel Comida_B;
    private javax.swing.JLabel Comida_C;
    private javax.swing.JLabel Comida_D;
    private javax.swing.JLabel Comida_E;
    private javax.swing.JLabel Comida_F;
    private javax.swing.JLabel Comida_G;
    private javax.swing.JLabel Comida_H;
    private javax.swing.JLabel Comida_I;

    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelJuego;
    // End of variables declaration//GEN-END:variables
}
